sapcc/openstack-audit-middleware

- auditmiddleware/__init__.py
- auditmiddleware/_api.py
- auditmiddleware/_notifier.py
- auditmiddleware/tests/unit/base.py
- auditmiddleware/tests/unit/test_audit_filter.py
- auditmiddleware/tests/unit/test_audit_oslo_messaging.py
- auditmiddleware/tests/unit/test_mappings.py
- etc/nova_audit_map.yaml
Perform sending of events to RabbitMQ in a background thread. Background thread and application communicate via a Python queue object that is in-memory. Usually that queue is empty. It will only fill up when the background thread starves or RabbitMQ is down / lagging.
The queue size is limited. In case of an overflow, all queue contents are written to the log. The contents of the queue will be lost when the application is stopped.
solves #4
> Nonblocking

- auditmiddleware/__init__.py
- auditmiddleware/_api.py
- auditmiddleware/tests/unit/base.py
- auditmiddleware/tests/unit/test_audit_filter.py
Support batch-create style APIs by pushing multiple events for such calls
required e.g. by the networks resource of neutron
Closes #9
> Support batch-create APIs

- auditmiddleware/_api.py
- auditmiddleware/tests/unit/base.py
the configuration of the payload filter in the mapping file was a bit inapt in that it was using a single attribute with comma-separated values to list the attributes to be included resp. excluded.
In a proper YAML syntax such lists should be represented by lists. And that was what the documentation claimed.
> fix include/exclude syntax

- .idea/inspectionProfiles/Project_Default.xml
- README.md
- auditmiddleware/_api.py
- auditmiddleware/tests/unit/base.py
- auditmiddleware/tests/unit/test_audit_filter.py
- auditmiddleware/tests/unit/test_audit_oslo_messaging.py
- auditmiddleware/tests/unit/test_mappings.py
- etc/nova_audit_map.yaml
- tox.ini
Those discovered resources are marked with an X-prefix, so they can be spotted easily.
Fixes #30
> Create events also for undeclared resources

- auditmiddleware/_api.py
- auditmiddleware/tests/unit/test_mappings.py
compute/agent ID is an integer, not a string. That oddity currently breaks event creation.
this PR handles such integer resource IDs properly and adds a regression unit test
> fix dump on integer resource ID

- .travis.yml
- README.md
- auditmiddleware/__init__.py
- auditmiddleware/_api.py
- auditmiddleware/_notifier.py
- auditmiddleware/tests/__init__.py
- auditmiddleware/tests/unit/__init__.py
- auditmiddleware/tests/unit/base.py
- auditmiddleware/tests/unit/test_audit_filter.py
- auditmiddleware/tests/unit/test_audit_middleware.py
- auditmiddleware/tests/unit/test_audit_oslo_messaging.py
- auditmiddleware/tests/unit/test_logging_notifier.py
- auditmiddleware/tests/unit/test_mappings.py
- auditmiddleware/tests/unit/utils.py
- etc/nova_audit_map.yaml
- test-requirements.txt
- tox.ini
The current implementation of attach_payload method removes sensitive information not just from the CADF event but also from the request payload dictionary passed as an input parameter.
Fortunately the webob request json property is implemented so inefficiently that it parses the request body and builds a new dictionary every time the property is read. This is to our rescue because otherwise our request would be damaged by attach_payload. It isn't so there should not be issues at runtime. Still this issue needs to be fixed since the webob behaviour is not guaranteed and any future change becomes more risky because of this.
I'll use the opportunity to fix the plethora of pep8 warnings, also adding documentation to many many places.
> Fix unwanted sideeffect of attach_payload on original request payload / Cleanup

- auditmiddleware/__init__.py
- auditmiddleware/tests/unit/test_audit_middleware.py
- lower-constraints.txt
Our auditmiddleware breaks downstream request processing by Glance because it replaces the request context with its own dictionary. Recent glance versions makes stricter assumptions on the request context's type which are not met by our own context.
Since this part of the code was copied from the original keystonemiddleware unchanged, we can also apply their fix.
Conclusions: Replacing parts of objects we do not own is a bad idea.
> fixing inherited keystonemiddleware bug 1809101

- auditmiddleware/_api.py
manila and cinder share/volume metadata were erroring `typeURI must not be None` because `rid='None'`
> fix singleton child id

- auditmiddleware/_api.py
Some parts of the code already guard against this, but some don't. This
leads to a problem in glance, where accessing `request.json` on a failed
image-upload (with content-type "application/octet-stream") can lead to
the auditmiddleware downloading the whole image body, which - for glance
- automatically ends up in a temporary file, because that's how the
WebOb library used by glance handles big WSGI request bodies.
We now only read `request.json` if the request has the appropriate
content-type.
An alternative would be to prohibit reading `request.json` if the
content-type is "application/octet-stream", but I'm not sure if we have
broken services out there, that support JSON in non-json requests.
> Don't read JSON from request of non application/json content-type

- setup.cfg
Since setuptools v54.1.0, the parmeters with dash have been deprecated in favor of the new parameters with underscore.
This change updates the parameters accordingly to avoid the warnings like the example below.
UserWarning: Usage of dash-separated 'description-file' will not be
supported in future versions. Please use the underscore name
'description_file' instead
https://github.com/pypa/setuptools/commit/a2e9ae4cb
> setup.cfg: Replace dashes with underscores

- auditmiddleware/_api.py
Add application credentials to audit logging. Looks reasonable to me.
> add app cred to audit logging

- auditmiddleware/_api.py
Reverts sapcc/openstack-audit-middleware#64 - Does not provide value for the given use case, or other use cases we can imagine.
> Revert "add app cred to audit logging"

- auditmiddleware/_api.py
This is intended to catch delete events that don't have project_id as part of their req.
> Add backup project_id in case of none for Neutron

- auditmiddleware/__init__.py
- auditmiddleware/_notifier.py
- auditmiddleware/tests/unit/test_audit_oslo_messaging.py
Add a configuration option, 'use_oslo_messaging', to indicate whether
to use oslo_messaging notifier. It is set to true for backwards
compatibility.
We can't use audit middleware with services like Swift, which have no
dependency on Oslo and does not work well with oslo_log. Swift uses rsyslog.
Currently, audit middleware chooses oslo_messaging if the
package is installed. This is problematic if Swift proxy is on the same
controller as any service which consumes oslo_messaging. With this new option,
Swift can now safely consume audit middleware by electing to use local
log notifier instead of oslo_messaging.
> Add option to disable using oslo_message notifier

- auditmiddleware/_notifier.py
the conf object is in the DEFAULT scope,
so we need to access first audit_middleware_notifications on it
> Fix access scope of use_oslo_messaging

- auditmiddleware/_api.py
nova tags put api command has an empty response text which causes a jsondecode error. Trying to fix by handling the case.
> fix put with empty response text

- auditmiddleware/_api.py
Some requests (like DELETE) have a content_length of None in their response. As trying to compare None with an integer raises an exception we need to make sure we have an int to compare to.
Without this patch a DELETE will trigger the following exception:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
> Handle requests with no content length

- auditmiddleware/_api.py
Trying to skip the binary issue here for the barbican payload endpoint while leaving everything else functioning normally.
> avoid binary issue with barbican payload endpoint

- auditmiddleware/_api.py
The audit middleware was assuming all contexts were dictionary-like objects,
causing AttributeError when handling Ironic requests where context is a
RequestContext object. This change adds proper type checking to safely handle
both dictionary and object-style contexts.
Error fixed:
AttributeError: 'RequestContext' object has no attribute 'get'
> Fix project_id handling for RequestContext objects

- auditmiddleware/_api.py
Fixing #114 
Null is used in the documentation etc to ignore a path. This does not function currently. Here is my attempt to fix.
> respect null in audit map

- auditmiddleware/_api.py
- test-requirements.txt
The Openstack Audit Middleware generates CADF events where the target.typeURI for failed or unknown operations on individual resource instances (like creating a server) incorrectly uses the collection-level type_uri (e.g., compute/servers) instead of the intended element-level el_type_uri (e.g., compute/server).
The current logic in _create_target_resource determines the target resource's typeURI primarily based on the presence of a successfully resolved resource ID (rid). This rid is typically extracted from the URL path (for PUT/DELETE/GET on /servers/{id}) or from the successful response payload of a creation operation (POST /servers).
When an operation targeting an instance fails before an ID can be determined (a POST /compute/servers call fails due to quota limits or invalid input, …
> Fix audit target URI for failed create operations
